-- AddColumns
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "usageCredits" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lastReset" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
